services:
  front:
    build: 
      './Front'
    ports:
      - "59152:8080"
      - "59153:8081"

  ffmpeg:
    build: 
      './MS_FFMpeg'
    ports:
      - "59163:8080"
      - "59164:8080"

  ytdlp:
    build: 
      './PAD-Spring_Boot'
    ports:
      - "59162:8080"

  mongo:
    image: 
      mongo
    restart: 
      always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes: 
      - dbdata:/data/db

  mongo-express:
    image: 
      mongo-express
    restart: 
      always
    ports:
      - 59165:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  dbdata: