name: CI/CD for Front Service

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and run docker-compose
        run: |
          docker-compose up -d

      - name: Test connection between front and ytdlp
        run: |
          sleep 10  # Give services time to start
          docker exec front curl -s http://ytdlp:8080 || exit 1

      - name: Push front service to DockerHub
        if: success()
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/front ./Front
          docker push ${{ secrets.DOCKER_USERNAME }}/front

      - name: Tear down docker-compose
        if: always()
        run: |
          docker-compose down
