name: CI/CD for Front Service

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker/docker-compose.yml"

      - name: Test connection between front and ytdlp
        run: |
          sleep 10  # Give services time to start
          docker exec front curl -s http://ytdlp:8080 || exit 1

      - name: Push front service to DockerHub
        if: success()
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/front ./Front
          docker push ${{ secrets.DOCKER_USERNAME }}/front

      - name: Tear down docker-compose
        if: always()
        run: |
          docker-compose down
